### ISSUE TITLE
스터디 진행 공지

### ISSUE THREAD

**Issue by LeeJaeHyeon05** [LeeJaeHyeon05/FirstApp#1]

**Comment by mmol93** [comment]
[Gather 모임 시간]
https://gather.town/app/DV5g4hlp5HkDrejJ/Kotlin%20study

1. 수요일 20:30 ~ 22:30
2. 토요일 16:00 ~ 18:00
3. 일요일 16:30 ~ 18:30

<br>
[First App 클론 코딩 대상]

https://play.google.com/store/apps/details?id=com.wuochoang.lolegacy&hl=ko&gl=US

<br>
[진행 방식]

1. 「롤 백과 - 롤 & 와일드 리프트 가이드」앱에서 DrawerLayout을 보면 여러 화면으로 나뉘어져 있습니다.
2. 이 중에서 원하는 것을 골라서 Issue에 페이지 이름을 등록합니다
3. 이 후 branch에 {자기이름+이슈번호}로 등록을 합니다 (예: jiwoo_#3)
develop branch에 있는 프로젝트를 base로 만드시면됩니다.
먼저 Issue를 등록하고 branch를 만드는 사람에게 화면 선택의 우선권이 있습니다.
4. 모임에서는 라이브러리・패키지 통일성, 프로젝트 방향성, 코딩하는 방법 등 여러 내용을 토의할 예정입니다.
