### ISSUE TITLE
룬 화면 제작

### ISSUE THREAD

**Issue by dongk00** [LeeJaeHyeon05/FirstApp#15]
안녕하세요! 11/10일에 합류한 김동화입니다! 스터디의 진행 방식을 아직 제대로 숙지하지 못했습니다ㅜ 일단 남는 페이지 중 룬 페이지 제작을 맡도록 하겠습니다.

![KakaoTalk_20211111_101611463](https://user-images.githubusercontent.com/77681440/141219716-8dc0bf68-78f4-404d-b400-fe6b070e917d.jpg)

![KakaoTalk_20211111_101611463_01](https://user-images.githubusercontent.com/77681440/141219720-3028af9b-3c1f-4b0f-9d4b-138f5ffdb8d4.jpg)

**Comment by mmol93** [comment]
안녕하세요!

일단 페이지 제작의 경우 navigation으로 페이지 이동을 하기 때문에 Activity가 아닌 fragment로 layout을 만드시면됩니다!

가능하시다면 delop branch에 있는 파일을 이용하여서 '룬화면' fragment를 만드신 후 navigation에 추가한 다음에

제작하시면 제일 좋을거 같습니다.(어려우시면 일단은 그냥 fragment에 만드시고 제가 나중에 옮겨서 merge 하는 형태로 하겠습니다.)

가능한한 만들어 보신 후 이번주 토요일 모임에서 어떤 부분을 통일하여 갈지 논의하기로 했으니 일단은 원하시는대로 진행하시면됩니다.

**Comment by dongk00** [comment]
넵 일단 능력 닿는데까지 공부해보겠습니다!

**Comment by dongk00** [comment]
모임은 오프라인으로 진행되나요? 시간대는 언제인가요?

**Comment by mmol93** [comment]
온라인으로 진행됩니다!

구체적인 시간대는 카톡 공지사항 보시면 있을거에요
