### ISSUE TITLE
Circle imageView 라이브러리

### ISSUE THREAD

**Issue by mmol93** [LeeJaeHyeon05/FirstApp#19]
롤백과 앱을 보시면 이미지의 경우 Circle imageView가 많습니다.

Glide를 사용하여 Circle imageView를 만들 수 있지만,

저는 아래의 라이브러리를 사용하여 항상 Circle ImageView를 만들었습니다.

https://github.com/hdodenhof/CircleImageView

일단 xml 파일에서 그냥 image 등록해서 사용하면 바로 Circle 형태로 나오며 Boarder 같은것도 쉽게 설정할 수 있습니다.

물론 Glide 라이브러리랑도 같이 사용할 수 있고요

다른 분들은 이 라이브러리 도입에 대해 어떻게 생각하는지 궁금합니다.

**Comment by kottodat** [comment]
작업 하는데 편의를 제공하는 다양한 라이브러리 들은 언제나 환영입니다.
오래된 재료나 낡은 수법으로 만든게 아닌 이상 서로 여러가지 라이브러리 들을 소개하고 사용 해보면 좋을 것 같습니다.

**Comment by asonetu** [comment]
네, 저도 적용해보는것에 찬성합니다.!
