### ISSUE TITLE
지금 API를 이용하여 챔피언 정보를 가져오는게 US인데 KR로 바꾸면 어떤가요...?

### ISSUE THREAD

**Issue by mmol93** [LeeJaeHyeon05/FirstApp#72]
현재 Retrofit에서 Champion 데이터를 가져오는 부분이 영어 버전을 읽어오는중인데 한글 버전을 처음부터 들고오는건 안되나요...?

아래의 데이터를 가져왔을 때 map 데이터의 key가 영문이면 한글과 영문명 둘 달 사용할 수 있을거 같습니다.

```
interface LeagueOfLegendsApi {
    //http://ddragon.leagueoflegends.com/cdn/11.22.1/data/en_US/champion.json
//    @GET("cdn/11.22.1/data/en_US/champion.json")
    @GET("cdn/11.22.1/data/en_US/champion/Aatrox.json")
    suspend fun getChampion(): Response<ChampionDetailVO>

    @GET("cdn/11.22.1/data/en_US/champion.json")
    suspend fun getAllChampion(): Response<ChampionVO>
}
```

key = 챔피언 영문명이 들어가 있음
Chapion 데이터의 name = 챔피언의 한글명 들어가 있음

이렇게요

**Comment by asonetu** [comment]
다국어 지원을 하려면 언어별 json 파일 모두 받고 DB table 로 언어별로 생성해줘야할 것 같네요;;
음. 영어, 한국어 2가지만 지원하는걸로 해도 될것 같긴 합니다.

**Comment by mmol93** [comment]
저랑 같은 생각이시군요... ㅋㅋ

**Comment by mmol93** [comment]
어제 보니까 이미 Champion 정보에 대한 DB가 있는거 같아서
시간 나면 챔피언 이름 한/영 전환 기능을 제가 넣어보도록 하겠습니다!
