### ISSUE TITLE
(해결) 리솔브 컨플릭트가 막혔습니다 

### ISSUE THREAD

**Issue by LeeJaeHyeon05** [LeeJaeHyeon05/FirstApp#86]
![에러12312313](https://user-images.githubusercontent.com/93363508/146306237-b7a492ed-60a7-450d-8189-401ee6a431e4.png)

---
밑에 둘러 보다가 컨플릭트 파일이 4개 정도 있어서 리솔브 컨플릭트 누를려고 하니 너무 많다고 고칠수가 없다고 하더라구요. 그 이런 상황이면 어디서 어떻게 고칠 수 있을까요

**Comment by mmol93** [comment]
https://github.com/LeeJaeHyeon05/FirstApp/pull/67
이 PR인가요?

**Comment by LeeJaeHyeon05** [comment]
네 그 pr 이에요
